steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/neuroflux-synapse-prod/synapse-repo/synapse-api:latest', './backend']

  # 2. Push the container image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/neuroflux-synapse-prod/synapse-repo/synapse-api:latest']

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'synapse-api' # This will be the name of our Cloud Run service
      - '--image=us-central1-docker.pkg.dev/neuroflux-synapse-prod/synapse-repo/synapse-api:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated' # Note: For now, we allow public access. We will secure this later.